// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMMJQly_kzjCtjBGg7M40vw6QhO_zgCHU',
    appId: '1:7303117190:web:8cad02be9ec02329e95407',
    messagingSenderId: '7303117190',
    projectId: 'resqnova-ffc7c',
    authDomain: 'resqnova-ffc7c.firebaseapp.com',
    storageBucket: 'resqnova-ffc7c.firebasestorage.app',
    measurementId: 'G-WSD206J2P0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwqWnqIhJLN21UgvsZDNUd242UrAMLOGs',
    appId: '1:7303117190:android:1547072697facdb5e95407',
    messagingSenderId: '7303117190',
    projectId: 'resqnova-ffc7c',
    storageBucket: 'resqnova-ffc7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbBfPveaImMCXyL-FZi2l9Uqm1XMlSVeU',
    appId: '1:7303117190:ios:28463ecb5b52cfc4e95407',
    messagingSenderId: '7303117190',
    projectId: 'resqnova-ffc7c',
    storageBucket: 'resqnova-ffc7c.firebasestorage.app',
    iosBundleId: 'com.example.resqnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbBfPveaImMCXyL-FZi2l9Uqm1XMlSVeU',
    appId: '1:7303117190:ios:28463ecb5b52cfc4e95407',
    messagingSenderId: '7303117190',
    projectId: 'resqnova-ffc7c',
    storageBucket: 'resqnova-ffc7c.firebasestorage.app',
    iosBundleId: 'com.example.resqnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMMJQly_kzjCtjBGg7M40vw6QhO_zgCHU',
    appId: '1:7303117190:web:71c065c05572eec1e95407',
    messagingSenderId: '7303117190',
    projectId: 'resqnova-ffc7c',
    authDomain: 'resqnova-ffc7c.firebaseapp.com',
    storageBucket: 'resqnova-ffc7c.firebasestorage.app',
    measurementId: 'G-8QLMGT8YE6',
  );
}
